# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5555:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
